version: '3.3'
services:
  todo-client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    container_name: todo-web-app
    networks:
      - todo

  nginx:
    depends_on:
      - todo-client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - todo

networks:
  todo:
    driver: bridge
